import Foundation

// MARK: - Audio Models
enum AudioType: String, CaseIterable, Identifiable, Codable {
    case beach = "sound-audio-beach"
    case birds = "sound-audio-birds"
    case campfire = "sound-audio-campfire"
    case desert = "sound-audio-desert"
    case forest = "sound-audio-forest"
    case lake = "sound-audio-lake"
    case meadow = "sound-audio-meadow"
    case nightDeep = "sound-audio-nightdeep"
    case nightLight = "sound-audio-nightlight"
    case rain = "sound-audio-rain"
    case river = "sound-audio-river"
    case seagulls = "sound-audio-seagulls"
    case thunder = "sound-audio-thunder"
    case underwater = "sound-audio-underwater"
    case whales = "sound-audio-whales"
    case cat = "sound-audio-cat"
    case bookPageTurning = "sound-audio-bookpageturning"
    case cafe = "sound-audio-cafe"
    case ventilator = "sound-audio-ventilator"
    case vinyl = "sound-audio-vinyl"
    case windBells = "sound-audio-windbells"
    case writingWithPencil = "sound-audio-writingwithpencil"
    case train = "sound-audio-train"
    case spaceship = "sound-audio-spaceship"
    case teapotBoiling = "sound-audio-teapotboiling"
    case slime = "sound-audio-slime"
    case oldTickingClock = "sound-audio-oldtickingclock"
    case grassSprinkler = "sound-audio-grasssprinkler"
    case iceCubes = "sound-audio-icecubes"
    case keyboard = "sound-audio-keyboard"
    case fan = "sound-audio-fan"
    case fizzyDrink = "sound-audio-fizzydrink"
    case blower = "sound-audio-blower"
    case aquarium = "sound-audio-aquarium"
    case airplane = "sound-audio-airplane"
    case bubbleWrap = "sound-audio-bubblewrap"
    case walkInTheWoods = "sound-audio-walkinthewoods"
    case walkInTheWater = "sound-audio-walkinthewater"
    case walkOnLeaves = "sound-audio-walkonleaves"
    case walkOnSnow = "sound-audio-walkonsnow"
    case whiteNoise = "sound-audio-whitenoise"
    case pinkNoise = "sound-audio-pinknoise"
    case blueNoise = "sound-audio-bluenoise"
    case brownNoise = "sound-audio-brownnoise"
    case greenNoise = "sound-audio-greennoise"
    case silence = "sound-audio-silence"

    var id: String { rawValue }
    
    var displayName: String {
        switch self {
        case .airplane: return "飞机"
        case .aquarium: return "水族馆"
        case .beach: return "海滩"
        case .birds: return "鸟鸣"
        case .blower: return "吹风机"
        case .blueNoise: return "蓝噪音"
        case .bookPageTurning: return "翻书声"
        case .brownNoise: return "棕噪音"
        case .bubbleWrap: return "气泡膜"
        case .cafe: return "咖啡馆"
        case .campfire: return "营火"
        case .cat: return "猫咪"
        case .desert: return "沙漠"
        case .fan: return "风扇"
        case .fizzyDrink: return "汽水"
        case .forest: return "森林"
        case .walkInTheWoods: return "树林漫步"
        case .grassSprinkler: return "洒水器"
        case .greenNoise: return "绿噪音"
        case .iceCubes: return "冰块"
        case .keyboard: return "键盘"
        case .lake: return "湖泊"
        case .river: return "河流"
        case .meadow: return "草地"
        case .nightDeep: return "深夜"
        case .nightLight: return "夜晚"
        case .oldTickingClock: return "钟表"
        case .pinkNoise: return "粉噪音"
        case .rain: return "雨声"
        case .seagulls: return "海鸥"
        case .silence: return "寂静"
        case .slime: return "史莱姆"
        case .spaceship: return "太空船"
        case .teapotBoiling: return "烧水壶"
        case .thunder: return "雷声"
        case .train: return "火车"
        case .underwater: return "水下"
        case .ventilator: return "通风扇"
        case .walkInTheWater: return "水中漫步"
        case .vinyl: return "黑胶唱片"
        case .walkOnLeaves: return "落叶漫步"
        case .walkOnSnow: return "雪地漫步"
        case .whales: return "鲸鱼"
        case .whiteNoise: return "白噪音"
        case .windBells: return "风铃"
        case .writingWithPencil: return "铅笔写字"
        }
    }
    
    var iconName: String {
        switch self {
        case .airplane: return "airplane"
        case .aquarium: return "fish"
        case .beach: return "beach.umbrella"
        case .birds: return "bird"
        case .blower: return "wind"
        case .blueNoise, .brownNoise, .greenNoise, .pinkNoise, .whiteNoise: return "waveform"
        case .bookPageTurning: return "book"
        case .bubbleWrap: return "bubble.right"
        case .cafe: return "cup.and.saucer"
        case .campfire: return "flame"
        case .cat: return "cat"
        case .desert: return "sun.max"
        case .fan, .ventilator: return "fan"
        case .fizzyDrink: return "bubbles.and.sparkles"
        case .forest: return "tree"
        case .walkInTheWoods: return "tree"
        case .grassSprinkler: return "sprinkler.and.droplets"
        case .iceCubes: return "cube"
        case .keyboard: return "keyboard"
        case .lake: return "water.waves"
        case .river: return "water.waves"
        case .meadow: return "camera.macro"
        case .nightDeep: return "moon.zzz"
        case .nightLight: return "moon.stars"
        case .oldTickingClock: return "clock"
        case .rain: return "cloud.rain"
        case .seagulls: return "bird.fill"
        case .silence: return "speaker.slash"
        case .slime: return "face.dashed"
        case .spaceship: return "globe.americas"
        case .teapotBoiling: return "humidifier"
        case .thunder: return "cloud.bolt"
        case .train: return "train.side.front.car"
        case .underwater: return "water.waves.and.arrow.trianglehead.down"
        case .walkInTheWater: return "water.waves"
        case .vinyl: return "record.circle"
        case .walkOnLeaves: return "leaf"
        case .walkOnSnow: return "snowflake"
        case .whales: return "fish"
        case .windBells: return "bell"
        case .writingWithPencil: return "pencil"
        }
    }
    
    var fileExtension: String {
        switch self {
        case .silence:
            return "mp3"
        default:
            return "m4a"
        }
    }
}
